# Tutorial 1 of Numpy

In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,6], np.int64)

In [4]:
arr

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [5]:
arr1=np.array([[4,5,6,7,8,9]])

In [6]:
arr1

array([[4, 5, 6, 7, 8, 9]])

In [7]:
arr1[0]

array([4, 5, 6, 7, 8, 9])

In [8]:
arr1[0,2]

6

In [9]:
arr2=np.array([[0,1,2,3,4],[5,6,7,8,9]])

In [10]:
arr2[0,1]

1

In [11]:
arr2[0,4]

4

In [12]:
arr3=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [13]:
arr3[1,1,2]

12

# Array Creation: conversion from other python structures

In [15]:
listarray= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [16]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
listarray.dtype

dtype('int32')

In [18]:
listarray.shape

(3, 3)

In [19]:
listarray.size

9

In [20]:
np.array({25,65,96})

array({96, 65, 25}, dtype=object)

# Intrinsic numpy array creation objects (eg:a-range, ones, zeros etc)

In [22]:
zeros=np.zeros((2,5))

In [23]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
zeros.dtype

dtype('float64')

In [25]:
zeros.shape

(2, 5)

In [26]:
rng=np.arange(15)

In [27]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
lspace=np.linspace(1,50,10)

In [29]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [30]:
lspace1=np.linspace(1,5,5)

In [31]:
lspace1

array([1., 2., 3., 4., 5.])

In [32]:
emp=np.empty((4,6))

In [33]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.11261706e-306, 7.56587584e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306, 1.42417221e-306],
       [7.56593017e-307, 1.37961302e-306, 6.89804132e-307,
        8.45610231e-307, 9.34601642e-307, 1.60217812e-306],
       [1.29060871e-306, 8.34445562e-308, 1.78022342e-306,
        8.06635958e-308, 8.34423493e-308, 2.10081501e-312]])

In [34]:
emp_like=np.empty_like(lspace)

In [35]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [36]:
ide=np.identity(45)

In [37]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [38]:
ide.shape

(45, 45)

In [39]:
arr= np.arange(99)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [41]:
arr.reshape(33,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89],
       [90, 91, 92],
       [93, 94, 95],
       [96, 97, 98]])

In [42]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [43]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [44]:
arr.shape

(99,)

**sum of axis: x axis and y axis**

In [45]:
x=([1,2,3],[4,5,6],[7,1,0])

In [46]:
ar=np.array(x)

In [47]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [48]:
ar.sum(axis=0)

array([12,  8,  9])

In [49]:
ar.sum(axis=1)

array([ 6, 15,  8])

**Transpose of array**

In [50]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [51]:
for item in ar.flat:
    print (item)

1
2
3
4
5
6
7
1
0


In [104]:
ar.ndim

2

In [106]:
ar.size

9

In [108]:
ar.nbytes

36

In [110]:
one=np.array([1,3,4,634,2])

In [112]:
one.argmax()

3

In [114]:
one.argmin()

0

In [116]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [118]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [120]:
ar.argmin()

8

In [126]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [128]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [130]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [132]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [136]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [140]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [144]:
ar2=np.array([[1,2,1],[4,0,6],[8,1,0]])

In [147]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [151]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [149]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [153]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [155]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [159]:
ar.sum()

29

In [161]:
ar.max()

7

In [163]:
ar.min()

0

In [165]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [171]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [173]:
type(np.where(ar>5))

tuple

In [175]:
np.count_nonzero(ar)

8

In [177]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [179]:
import sys

In [181]:
py_ar=[0,4,55,2]

In [183]:
np_ar=np.array(py_ar)

In [187]:
sys.getsizeof(1) * len(py_ar)

112

In [191]:
np_ar.itemsize*np_ar.size

16